import { Channel, Movie, HeroItem } from '../types';

// Usando imagens do TMDB/placeholder para desenvolvimento
const TMDB_IMG = 'https://image.tmdb.org/t/p/w500';
const BACKDROP = 'https://image.tmdb.org/t/p/w1280';

export const HERO_ITEMS: HeroItem[] = [
  {
    id: 'h1',
    title: 'Duna: Parte Dois',
    description: 'Paul Atreides une forças com os Fremen enquanto busca vingança contra os conspiradores que destruíram sua família.',
    backdrop: `${BACKDROP}/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg`,
    type: 'movie',
    ageRating: '12',
    genres: ['Ficção Científica', 'Ação', 'Drama'],
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
  {
    id: 'h2',
    title: 'The Last of Us',
    description: 'Um sobrevivente endurecido atravessa o que restou dos EUA com uma garota que pode ser a última esperança da humanidade.',
    backdrop: `${BACKDROP}/uDgy6hyPd1To1g4xyzBbktOQ8WL.jpg`,
    type: 'serie',
    ageRating: '16',
    genres: ['Drama', 'Terror', 'Ação'],
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
  {
    id: 'h3',
    title: 'SporTV',
    description: 'Cobertura completa dos principais eventos esportivos ao vivo.',
    backdrop: `${BACKDROP}/hYZ4a0JvPETdfgJJ2r1cDg7k5kS.jpg`,
    type: 'channel',
    ageRating: 'L',
    genres: ['Esportes'],
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
];

export const CHANNELS: Channel[] = [
  {
    id: 'c1',
    name: 'Globo',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Rede_Globo_logo_2021.svg/200px-Rede_Globo_logo_2021.svg.png',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'TV Aberta',
    country: 'Brasil',
    language: 'Português',
    isLive: true,
    viewers: 41200,
    ageRating: 'L',
    currentProgram: 'Jornal Nacional',
    nextProgram: 'Fantástico',
    isFeatured: true,
  },
  {
    id: 'c2',
    name: 'SporTV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Logotipo_do_SporTV.svg/200px-Logotipo_do_SporTV.svg.png',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'Esportes',
    country: 'Brasil',
    language: 'Português',
    isLive: true,
    viewers: 18500,
    ageRating: 'L',
    currentProgram: 'Brasileirão Ao Vivo',
    isFeatured: true,
  },
  {
    id: 'c3',
    name: 'CNN Brasil',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/CNN_Brasil_2022.svg/200px-CNN_Brasil_2022.svg.png',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'Notícias',
    country: 'Brasil',
    language: 'Português',
    isLive: true,
    viewers: 9300,
    ageRating: 'L',
    currentProgram: 'CNN Prime Time',
  },
  {
    id: 'c4',
    name: 'Discovery',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Discovery_Channel_-_Logo.svg/200px-Discovery_Channel_-_Logo.svg.png',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'Documentários',
    country: 'EUA',
    language: 'Inglês',
    isLive: true,
    viewers: 7100,
    ageRating: 'L',
    currentProgram: 'Planeta Oceano',
  },
  {
    id: 'c5',
    name: 'MTV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/MTV_2021_logo.svg/200px-MTV_2021_logo.svg.png',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'Música',
    country: 'EUA',
    language: 'Português',
    isLive: true,
    viewers: 5400,
    ageRating: '14',
    currentProgram: 'Top 20',
  },
  {
    id: 'c6',
    name: 'Cartoon Network',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/200px-Cartoon_Network_2010_logo.svg.png',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'Infantil',
    country: 'EUA',
    language: 'Português',
    isLive: true,
    viewers: 12800,
    ageRating: 'L',
    currentProgram: 'Ben 10',
  },
  {
    id: 'c7',
    name: 'Band',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Logo_band.svg/200px-Logo_band.svg.png',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'TV Aberta',
    country: 'Brasil',
    language: 'Português',
    isLive: true,
    viewers: 8900,
    ageRating: 'L',
    currentProgram: 'Brasil Urgente',
  },
  {
    id: 'c8',
    name: 'ESPN',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/ESPN_wordmark.svg/200px-ESPN_wordmark.svg.png',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    category: 'Esportes',
    country: 'EUA',
    language: 'Português',
    isLive: true,
    viewers: 14200,
    ageRating: 'L',
    currentProgram: 'SportsCenter',
    isFeatured: true,
  },
];

export const MOVIES: Movie[] = [
  {
    id: 'm1',
    title: 'Duna: Parte Dois',
    poster: `${TMDB_IMG}/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg`,
    backdrop: `${BACKDROP}/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg`,
    year: 2024,
    duration: 166,
    rating: 8.5,
    ageRating: '12',
    genres: ['Ficção Científica', 'Ação'],
    description: 'Paul Atreides une forças com os Fremen enquanto busca vingança.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    isFeatured: true,
    isNew: true,
  },
  {
    id: 'm2',
    title: 'Oppenheimer',
    poster: `${TMDB_IMG}/8Gxv8giaFOGOlrzOMtQQ6kTPmgz.jpg`,
    backdrop: `${BACKDROP}/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg`,
    year: 2023,
    duration: 180,
    rating: 8.9,
    ageRating: '14',
    genres: ['Drama', 'Histórico'],
    description: 'A história do físico americano J. Robert Oppenheimer.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    isFeatured: true,
  },
  {
    id: 'm3',
    title: 'Poor Things',
    poster: `${TMDB_IMG}/kCGlIMHnOm8JPXEGhDzeTuHGSRZ.jpg`,
    backdrop: `${BACKDROP}/3OwHg7xAMcNhDvKBtGYI3mGJlYP.jpg`,
    year: 2023,
    duration: 141,
    rating: 8.0,
    ageRating: '16',
    genres: ['Drama', 'Ficção Científica', 'Comédia'],
    description: 'Uma jovem ressuscitada por um cientista excêntrico foge para conhecer o mundo.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    isNew: true,
  },
  {
    id: 'm4',
    title: 'Killers of the Flower Moon',
    poster: `${TMDB_IMG}/dB6jEFTfBq00L9bsJMyFGzV5oFP.jpg`,
    backdrop: `${BACKDROP}/1X7vow16X7CnCoexXh4H4F2yDJv.jpg`,
    year: 2023,
    duration: 206,
    rating: 7.6,
    ageRating: '14',
    genres: ['Crime', 'Drama', 'Histórico'],
    description: 'Membros da nação Osage são assassinados misteriosamente nos anos 1920.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
  {
    id: 'm5',
    title: 'Wonka',
    poster: `${TMDB_IMG}/qhb1qOilapbapxWQn9jtRCMwXJF.jpg`,
    backdrop: `${BACKDROP}/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg`,
    year: 2023,
    duration: 116,
    rating: 7.0,
    ageRating: 'L',
    genres: ['Fantasia', 'Comédia', 'Família'],
    description: 'A história de como o jovem Willy Wonka se tornou o chocolateiro mais famoso do mundo.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    isNew: true,
  },
  {
    id: 'm6',
    title: 'Priscilla',
    poster: `${TMDB_IMG}/lNJPsHPDDhqMbhPiKZLRiWUzGzN.jpg`,
    backdrop: `${BACKDROP}/rqbCbjLP4oHQ09KvGKHDcBkRmG4.jpg`,
    year: 2023,
    duration: 113,
    rating: 6.8,
    ageRating: '12',
    genres: ['Drama', 'Romance', 'Biografia'],
    description: 'A vida de Priscilla Presley com Elvis Presley.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  },
];

export const CATEGORIES_LIST = [
  { id: 'all', label: 'Todos', icon: 'grid' },
  { id: 'tv', label: 'TV Aberta', icon: 'tv' },
  { id: 'sports', label: 'Esportes', icon: 'football' },
  { id: 'movies', label: 'Filmes', icon: 'film' },
  { id: 'series', label: 'Séries', icon: 'play-circle' },
  { id: 'news', label: 'Notícias', icon: 'newspaper' },
  { id: 'kids', label: 'Infantil', icon: 'happy' },
  { id: 'docs', label: 'Documentários', icon: 'earth' },
  { id: 'music', label: 'Música', icon: 'musical-notes' },
  { id: 'international', label: 'Internacional', icon: 'globe' },
] as const;
